server:
  port: ${sport.serve.port}

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${sport.datasource.driver-class-name}
      url: jdbc:mysql://${sport.datasource.host}:${sport.datasource.port}/${sport.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${sport.datasource.username}
      password: ${sport.datasource.password}



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sport.entity
  #开启数据库命名与Java驼峰命名的转换
  configuration:
    map-underscore-to-camel-case: true


sport:
  jwt:
    admin-secret-key: ${sport.jwt.admin-secret-key}
    admin-ttl: ${sport.jwt.admin-ttl}
    admin-token-name: ${sport.jwt.admin-token-name}
    user-secret-key: ${sport.jwt.user-secret-key}
    user-ttl: ${sport.jwt.user-ttl}
    uer-token-name: ${sport.jwt.uer-token-name}

  wechat:
      appid: ${sport.wechat.appid}
      secret: ${sport.wechat.secret}


#输出日志
logging:
  level:
    com:
      sport:
        mapper: debug
        service: info
        controller: info