sport:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: poetic_harmony_sport
    username: root
    password: 123456
  serve:
    port: 8080